export const REDUCTION_TIPS = [
  {
    id: 'tip-1',
    title: 'Choose Clean Transportation',
    description: 'Carpool, use electric vehicles, or switch to public transit and active commuting whenever possible.',
    category: 'Transport',
  },
  {
    id: 'tip-2',
    title: 'Stop Open Waste Burning',
    description: 'Avoid open waste burning and promptly report illegal garbage or crop burning events to municipal authorities.',
    category: 'Community',
  },
  {
    id: 'tip-3',
    title: 'Adopt Clean Cooking Fuel',
    description: 'Switch to LPG, induction, or low-emission clean fuels instead of biomass or unvented coal stoves.',
    category: 'Home',
  },
  {
    id: 'tip-4',
    title: 'Support Urban Greenery',
    description: 'Participate in neighborhood tree plantation drives and support urban green space protection initiatives.',
    category: 'Environment',
  },
  {
    id: 'tip-5',
    title: 'Segregate Household Waste',
    description: 'Segregate waste into biodegradable, recyclable, and hazardous categories to minimize landfill gas emissions.',
    category: 'Waste Management',
  },
  {
    id: 'tip-6',
    title: 'Energy Efficiency at Home',
    description: 'Use BEE 5-star rated appliances, LED lighting, and turn off standby electronics to lower power plant load.',
    category: 'Energy',
  },
];

export const GOVERNMENT_POLICIES = [
  {
    id: 'policy-1',
    title: 'National Clean Air Programme (NCAP)',
    description: 'A comprehensive long-term national framework to tackle air pollution across 131 non-attainment cities in India.',
    objective: 'Target 20%–40% reduction in PM2.5 and PM10 concentrations by 2026 compared to 2017 levels.',
    impact: 'Establishes city-specific action plans, continuous ambient air monitoring stations, and source apportionment studies.',
    url: 'https://cpcb.nic.in/ncap-management/',
  },
  {
    id: 'policy-2',
    title: 'Bharat Stage VI (BS6) Emission Standards',
    description: 'Stringent vehicle emission standards mandating ultra-low sulfur fuel (10 ppm) and advanced exhaust filters.',
    objective: 'Reduce vehicular nitrogen oxides (NOx) and particulate matter emissions by up to 80%–90%.',
    impact: 'Dramatically reduces tailpipe emissions across all newly manufactured passenger, commercial, and heavy vehicles.',
    url: 'https://morth.nic.in/',
  },
  {
    id: 'policy-3',
    title: 'FAME India Scheme (Electric Mobility)',
    description: 'Faster Adoption and Manufacturing of (Hybrid &) Electric Vehicles to accelerate clean urban transport.',
    objective: 'Incentivize commercial EV fleets, public electric buses, and widespread charging infrastructure deployment.',
    impact: 'Phases out urban fossil fuel dependence, curbing tailpipe emissions in high-density metropolitan areas.',
    url: 'https://fame2.heavyindustries.gov.in/',
  },
  {
    id: 'policy-4',
    title: 'City Construction & Dust Control Rules',
    description: 'Mandatory dust mitigation guidelines enforced across urban civil construction and demolition sites.',
    objective: 'Prevent fugitive PM10 and PM2.5 dust from unpaved roads, construction sites, and debris transit.',
    impact: 'Requires anti-smog guns, green barrier netting, water mist sprinklers, and strict violation fines.',
    url: 'https://cpcb.nic.in/',
  },
  {
    id: 'policy-5',
    title: 'Perform, Achieve & Trade (PAT) Scheme',
    description: 'A market-based regulatory mechanism to enhance energy efficiency in energy-intensive industrial sectors.',
    objective: 'Set specific energy consumption reduction targets for energy-heavy industrial units.',
    impact: 'Drives industrial boiler modernization, cleaner fuel transitions, and lower industrial emissions footprints.',
    url: 'https://beeindia.gov.in/',
  },
  {
    id: 'policy-6',
    title: 'Renewable Energy Development Programs',
    description: 'National initiatives accelerating solar, wind, and green hydrogen power generation capacity.',
    objective: 'Achieve 50% cumulative electric power installed capacity from non-fossil fuel energy resources by 2030.',
    impact: 'Phases down thermal coal dependence, reducing power sector sulfur dioxide (SO2) and carbon output.',
    url: 'https://mnre.gov.in/',
  },
];

export const EDUCATIONAL_READS = [
  {
    id: 'read-1',
    title: 'How AQI Impacts Daily Lifestyle Decisions',
    source: 'WHO',
    readTime: '4 min read',
    summary: 'Discover how daily Air Quality Index readings guide healthy choices for exercise, outdoor exposure, sensitive populations, and personal protective equipment.',
    keyTakeaway: 'Monitoring real-time AQI allows individuals to dynamically adjust outdoor schedules, reducing chronic cardiopulmonary health risks.',
    url: 'https://www.who.int/news-room/fact-sheets/detail/ambient-(outdoor)-air-quality-and-health',
  },
  {
    id: 'read-2',
    title: 'Top 10 Home Changes to Reduce Pollution Exposure',
    source: 'EPA',
    readTime: '5 min read',
    summary: 'Practical household strategies to minimize indoor air pollution, optimize cross-ventilation, select HEPA air purifiers, and reduce indoor VOC sources.',
    keyTakeaway: 'Indoor air quality can often be 2 to 5 times more polluted than outdoor air; simple ventilation and filtration habits significantly lower exposure.',
    url: 'https://www.epa.gov/indoor-air-quality-iaq',
  },
  {
    id: 'read-3',
    title: 'Why Community Reporting Improves Air Governance',
    source: 'OpenAQ',
    readTime: '3 min read',
    summary: 'How public crowd-sourced pollution reporting and open data platforms bridge monitoring gaps and hold municipal authorities accountable.',
    keyTakeaway: 'Open environmental data and hyper-local community reporting accelerate policy interventions and targeted pollution enforcement.',
    url: 'https://openaq.org/',
  },
  {
    id: 'read-4',
    title: 'Understanding Indoor Air Pollution & Health Risks',
    source: 'UNEP',
    readTime: '4 min read',
    summary: 'A deep dive into common indoor air hazards such as cooking smoke, particulate matter, mold spores, and volatile organic compounds.',
    keyTakeaway: 'Clean fuel transitions and proper indoor ventilation prevent millions of premature respiratory illnesses globally.',
    url: 'https://www.unep.org/',
  },
  {
    id: 'read-5',
    title: 'Role of Citizen Science in Monitoring Air Quality',
    source: 'NCAP / CPCB',
    readTime: '5 min read',
    summary: 'How affordable optical sensor networks and public participation empower citizens to gather neighborhood air quality telemetry.',
    keyTakeaway: 'Citizen-led data collection complements government monitoring grids, pinpointing localized micro-hotspots.',
    url: 'https://cpcb.nic.in/',
  },
];
